### ISSUE TITLE
The game breaks when extinguishing fire.

### ISSUE THREAD

**Issue by Nevol2110** [NilanthAnimosus/Barotrauma---Nilanths-Edits#1]
Barotrauma Client crash report (generated on 26.02.2018 11:08:11)

Barotrauma seems to have crashed. Sorry for the inconvenience! 
If you'd like to help fix the bug that caused the crash, please send this file to the developers on the Undertow Games forums.

Game version 0.8.0.4 NILMOD SERVER MODIFICATION
Graphics mode: 1280x720 (BorderlessWindowed)
Selected content package: Vanilla 0.8
Level seed: fWLADwef
Loaded submarine: Aegir Mark III (Mod) (935C627FB686E2162C4729B2F513F6C4)
Selected screen: Barotrauma.GameScreen
Server (Round had started)

System info:
    Operating system: Microsoft Windows NT 6.2.9200.0 64 bit
    GPU name: NVIDIA GeForce 940MX
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

This was running NilMod Code!

Exception: Коллекция была изменена; невозможно выполнить операцию перечисления.
Target site: Void ThrowInvalidOperationException(System.ExceptionResource)
Stack trace: 
   в System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   в System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   в System.Collections.Generic.List`1.Enumerator.MoveNext()
   в Barotrauma.Items.Components.RepairTool.Repair(Vector2 rayStart, Vector2 rayEnd, Single deltaTime, Character user, Single degreeOfSuccess, List`1 ignoredBodies) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Items\Components\Holdable\RepairTool.cs:строка 195
   в Barotrauma.Items.Components.RepairTool.Use(Single deltaTime, Character character) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Items\Components\Holdable\RepairTool.cs:строка 123
   в Barotrauma.Item.Use(Single deltaTime, Character character) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Items\Item.cs:строка 1163
   в Barotrauma.Character.Control(Single deltaTime, Camera cam) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:строка 1312
   в Barotrauma.Character.Update(Single deltaTime, Camera cam) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:строка 1980
   в Barotrauma.Character.UpdateAll(Single deltaTime, Camera cam) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Characters\Character.cs:строка 1818
   в Barotrauma.GameScreen.Update(Double deltaTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaShared\Source\Screens\GameScreen.cs:строка 151
   в Barotrauma.GameMain.Update(GameTime gameTime) в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\GameMain.cs:строка 471
   в Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.Tick()
   в MonoGame.Framework.WinFormsGameWindow.RunLoop()
   в MonoGame.Framework.WinFormsGamePlatform.RunLoop()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Barotrauma.Program.Main() в F:\Barotrauma\BT NilEdit\Barotrauma---Nilanths-Edits\Barotrauma\BarotraumaClient\Source\Program.cs:строка 47

Last debug messages:
   [26.02.2018 11:08:10] Fire spawning off
   [26.02.2018 11:08:10] fire
   [26.02.2018 11:08:07] Fire spawning on
   [26.02.2018 11:08:07] fire
   [26.02.2018 11:07:13] No clients voted a submarine, choosing default submarine: Barotrauma.Submarine (Aegir Mark III (Mod))
   [26.02.2018 11:06:26] Enter "help" for a list of available console commands

**Comment by NilanthAnimosus** [comment]
This should be fixed in the last version I uploaded, if you are using the version labeled "25/02/2018-4" as that added a null check.

If its still occurring on that version of the mod I'll change it until I can get it to stop crashing with a few modifications and a try catch until its no longer needed.

Scratch the above, I did something silly and I've fixed the issue properly now once I get around to committing it.
