### ISSUE TITLE
Feature request - Revive on sub

### ISSUE THREAD

**Issue by Momiro** [NilanthAnimosus/Barotrauma---Nilanths-Edits#5]
In addition to the respawn on submarine option, a revive on the submarine if your body is still there would be nice, and would help to reduce clutter on respawns.

**Comment by NilanthAnimosus** [comment]
If your talking of the InGameInfo GUI. the heal button is also a revive button

Most of those buttons have dual functions which you can hover over the icon to read.

I don't think I've added a command yet to respawn to submarine on a perclient basis,

I also don't think it'd be a great idea if one were to keep reusing the previous body, for instance when the body has effectively been blown to bits, robbed of all essential items and such, left in some obscure location without any way to get out, being revived handcuffed....etc

The revive commands also automatically try to force the client back into control wherever applicable.


I could make it an option however so if the player has a previous body it will attempt to use it if its on the main submarine, but generally it isn't the best idea gameplay wise, players would if anything get annoyed by the problems it would cause.

The GUI has methods for corpse cleanup - perhaps I will convert these into some form of commands.

**Comment by Momiro** [comment]
I would like the corpse cleanup, and any missing features from commands to be ported to commands, as I mainly run my server from a linux VPS. 
And I can definitely understand the issues with respawning your own corpse.
Is there a way to use the features from the GUI as a client connected to a server, provided you have permissions?
Actually now that I think of it, players looting bodies and having them respawn back on the ship, as long as they weren't dismembered or had their avatar damaged too much to use, might be an interesting mechanic for roleplay, a competent crew could stow a griefer in a box, or a crew could take over the ship in a mutiny without worry of another captain spawning in...

**Comment by NilanthAnimosus** [comment]
Its something I have not coded yet, there was a Client version of the ingameinfo GUI in the works along with the structure to make them Client->Server commands later, but I have not gotten  around to implementing any of it properly.

Anything that sounds beneficial can also be extremely negative, such as griefers taking over a submarine and keeping the bodies locked up and cuffed in a room to die over and over, while reconnecting just puts them back there.

**Comment by Momiro** [comment]
That would definitely be bad, maybe a setting to give a new body on disconnect?

**Comment by NilanthAnimosus** [comment]
revival code in nilmod tries to find the appropriate client to a body being revived, and it has no way to know if the client just rejoined or not, nor would I want to add tracking of it just to implement that.

It would finally be odd to have clients have to be aware they need to disconnect in order to reset it, going into fairly odd territory now. corpse cleanup is a better concept than reviving to previous bodies trust me.
