### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ghost** [NilanthAnimosus/Barotrauma---Nilanths-Edits#7]
it will work but not properly, I cant see mobs and shiet

**Comment by escept** [comment]
This project is not being maintained anymore.

**Comment by NilanthAnimosus** [comment]
It shouldn't work/be used, at least from this projects code or my releases on the forums first page,  Its a full executable replacement for barotrauma, it is too far out of date.

Use the undertow games forums (Look for this mods project page) and find landongamers download, he has been keeping it updated (Plus/minus a few bugs) and messaging me over time, though I intend to update it myself when I have proper time.

I won't be resuming any form of work until after Christmas / towards January when I have more time to.
